# Generated by Django 5.2.3 on 2025-06-18 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('min_temp', models.FloatField(help_text='Temperatura mínima ideal (°C)')),
                ('max_temp', models.FloatField(help_text='Temperatura máxima ideal (°C)')),
                ('min_humidity', models.FloatField(help_text='Humedad mínima ideal (%)')),
                ('max_humidity', models.FloatField(help_text='Humedad máxima ideal (%)')),
                ('care_instructions', models.TextField(help_text='Instrucciones generales de cuidado')),
            ],
        ),
    ]
